### ISSUE TITLE
push phase of `draft up` twirls forever when specifying an invalid registry

### ISSUE THREAD

**Issue by jpetazzo** [Azure/draft#907]
## What I do

Lack caffeine. Specify a wrong registry configuration. Run `draft up`:
```bash
draft config set registry jpetazzo/testdraft
draft up
```

## What I expect

When getting to the "push" phase, Draft tells me that the registry is invalid.
(And instructs me to caffeinate :coffee:  )

## What I see instead

Push phase twirls forever:
```
$ draft up
Draft Up Started: 'todos-api': 01CYCR40DFJQX6XBFZ3RPGEGWE
todos-api: Building Docker Image: SUCCESS ⚓  (1.0004s)
todos-api: Pushing Docker Image -
```

## Additional details

```
$ draft version
&version.Version{SemVer:"v0.16.0", GitCommit:"5433afea1421810ae9d828631d8651de913b347a", GitTreeState:"dirty"}
```

I'm using the Go demo app from the draft repo.

On my local machine, logged as `jpetazzo` to the Docker Hub (confirmed by pushing successfully to `jpetazzo/testdraft:busybox` with `docker push`), `draft config set registry invalid ; draft up` gets me a timeout. On another machine without credential information, at some point, it got me a panic (which I can't seem to reproduce now):

```
$ draft up
Draft Up Started: 'todos-api': 01CYCQXX933ZY87BYCFT70R6CZ
todos-api: Building Docker Image: SUCCESS ⚓  (1.0004s)
todos-api: Pushing Docker Image -panic: send on closed channel

goroutine 40 [running]:
github.com/Azure/draft/pkg/builder/docker.(*Builder).Push.func1.1(0xc42049c8e0, 0xc4202060d0, 0x244fec0, 0xc420016088, 0xc42049d6f4, 0x4, 0xc420372060, 0xc420298460, 0xc42033d8c0, 0x3a)
	/go/src/github.com/Azure/draft/pkg/builder/docker/builder.go:134 +0x2af
created by github.com/Azure/draft/pkg/builder/docker.(*Builder).Push.func1
	/go/src/github.com/Azure/draft/pkg/builder/docker/builder.go:122 +0x149
```

**Comment by pqhung1983** [comment]
the same issues on me, push phase was twirling forever when using Alibaba private registry: registry-intl.ap-southeast-5.aliyuncs.com
I also check the logs on $DRAFT_HOME . It is stuck  on preparing....
```$ tail -f ~/.draft/logs/testing/01D1Z9B867Q5X33BGCHEWP2P8Z
1c862c0e1a30: Preparing
7bff100f35cb: Preparing
2d0aa4be105c: Waiting
a2d46b2e43c5: Waiting
4c9e5faf181d: Waiting
e911107288dd: Waiting
03ecf0b0f1d6: Waiting
ce1e31a85f79: Waiting
1c862c0e1a30: Waiting
7bff100f35cb: Waiting
```
